/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnippetsCreateRouteImport } from './routes/snippets/create'
import { Route as SnippetsFiltersRouteImport } from './routes/snippets/_filters'
import { Route as SnippetsFiltersIndexRouteImport } from './routes/snippets/_filters.index'
import { Route as SnippetsSnippetIdIndexRouteImport } from './routes/snippets/$snippetId/index'
import { Route as SnippetsSnippetIdEditRouteImport } from './routes/snippets/$snippetId/edit'

const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsCreateRoute = SnippetsCreateRouteImport.update({
  id: '/snippets/create',
  path: '/snippets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsFiltersRoute = SnippetsFiltersRouteImport.update({
  id: '/snippets/_filters',
  path: '/snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsFiltersIndexRoute = SnippetsFiltersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SnippetsFiltersRoute,
} as any)
const SnippetsSnippetIdIndexRoute = SnippetsSnippetIdIndexRouteImport.update({
  id: '/snippets/$snippetId/',
  path: '/snippets/$snippetId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsSnippetIdEditRoute = SnippetsSnippetIdEditRouteImport.update({
  id: '/snippets/$snippetId/edit',
  path: '/snippets/$snippetId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hello': typeof HelloRoute
  '/snippets': typeof SnippetsFiltersRouteWithChildren
  '/snippets/create': typeof SnippetsCreateRoute
  '/snippets/$snippetId/edit': typeof SnippetsSnippetIdEditRoute
  '/snippets/$snippetId/': typeof SnippetsSnippetIdIndexRoute
  '/snippets/': typeof SnippetsFiltersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hello': typeof HelloRoute
  '/snippets/create': typeof SnippetsCreateRoute
  '/snippets/$snippetId/edit': typeof SnippetsSnippetIdEditRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdIndexRoute
  '/snippets': typeof SnippetsFiltersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hello': typeof HelloRoute
  '/snippets/_filters': typeof SnippetsFiltersRouteWithChildren
  '/snippets/create': typeof SnippetsCreateRoute
  '/snippets/$snippetId/edit': typeof SnippetsSnippetIdEditRoute
  '/snippets/$snippetId/': typeof SnippetsSnippetIdIndexRoute
  '/snippets/_filters/': typeof SnippetsFiltersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hello'
    | '/snippets'
    | '/snippets/create'
    | '/snippets/$snippetId/edit'
    | '/snippets/$snippetId/'
    | '/snippets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hello'
    | '/snippets/create'
    | '/snippets/$snippetId/edit'
    | '/snippets/$snippetId'
    | '/snippets'
  id:
    | '__root__'
    | '/'
    | '/hello'
    | '/snippets/_filters'
    | '/snippets/create'
    | '/snippets/$snippetId/edit'
    | '/snippets/$snippetId/'
    | '/snippets/_filters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelloRoute: typeof HelloRoute
  SnippetsFiltersRoute: typeof SnippetsFiltersRouteWithChildren
  SnippetsCreateRoute: typeof SnippetsCreateRoute
  SnippetsSnippetIdEditRoute: typeof SnippetsSnippetIdEditRoute
  SnippetsSnippetIdIndexRoute: typeof SnippetsSnippetIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/create': {
      id: '/snippets/create'
      path: '/snippets/create'
      fullPath: '/snippets/create'
      preLoaderRoute: typeof SnippetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/_filters': {
      id: '/snippets/_filters'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof SnippetsFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/_filters/': {
      id: '/snippets/_filters/'
      path: '/'
      fullPath: '/snippets/'
      preLoaderRoute: typeof SnippetsFiltersIndexRouteImport
      parentRoute: typeof SnippetsFiltersRoute
    }
    '/snippets/$snippetId/': {
      id: '/snippets/$snippetId/'
      path: '/snippets/$snippetId'
      fullPath: '/snippets/$snippetId/'
      preLoaderRoute: typeof SnippetsSnippetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/$snippetId/edit': {
      id: '/snippets/$snippetId/edit'
      path: '/snippets/$snippetId/edit'
      fullPath: '/snippets/$snippetId/edit'
      preLoaderRoute: typeof SnippetsSnippetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SnippetsFiltersRouteChildren {
  SnippetsFiltersIndexRoute: typeof SnippetsFiltersIndexRoute
}

const SnippetsFiltersRouteChildren: SnippetsFiltersRouteChildren = {
  SnippetsFiltersIndexRoute: SnippetsFiltersIndexRoute,
}

const SnippetsFiltersRouteWithChildren = SnippetsFiltersRoute._addFileChildren(
  SnippetsFiltersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelloRoute: HelloRoute,
  SnippetsFiltersRoute: SnippetsFiltersRouteWithChildren,
  SnippetsCreateRoute: SnippetsCreateRoute,
  SnippetsSnippetIdEditRoute: SnippetsSnippetIdEditRoute,
  SnippetsSnippetIdIndexRoute: SnippetsSnippetIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
